<?php
/**
 * Where invoice PDFs live, and who is allowed to have one.
 *
 * Two independent defences, because they fail on different servers:
 *
 *   1. The directory is denied by .htaccess and carries an index.php, so on
 *      Apache nothing under it is web-reachable at all.
 *   2. The filename carries a site-secret hash, so on nginx — where .htaccess
 *      is inert and the deny does nothing — the URL still cannot be guessed
 *      from the order number.
 *
 * Neither is the real gate. The real gate is qhta_woo_invoice_can_access(),
 * which every download goes through; the two above only stop the file being
 * fetched around it.
 *
 * @package QHTA_Woo_Invoice
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Order meta: the basename of the generated PDF.
 *
 * The path is derivable, so this is not strictly needed to find the file. It is
 * stored because it is the honest answer to "has this order been invoiced, and
 * under what name?" — including after the filename hash changes (see
 * qhta_woo_invoice_filename()), when the derived name and the stored one
 * disagree and the stored one is the file actually on disk.
 */
const QHTA_WOO_INVOICE_META_FILE = '_qhta_woo_invoice_file';

/**
 * Order meta: when the PDF was last written, as a Unix timestamp.
 */
const QHTA_WOO_INVOICE_META_TIME = '_qhta_woo_invoice_generated';

/**
 * Absolute path to the invoice directory, with a trailing slash.
 *
 * Inside uploads rather than inside the plugin so invoices — and the template
 * override that sits beside them — survive a plugin update, which replaces the
 * plugin directory wholesale.
 *
 * @return string
 */
function qhta_woo_invoice_dir() {
	$uploads = wp_upload_dir();

	return trailingslashit( $uploads['basedir'] ) . 'qhta-woo-invoice/';
}

/**
 * Create the invoice directory and lock it down.
 *
 * Idempotent and cheap to call: once the two guard files exist it does nothing
 * but stat them, so generation can call it every time rather than assuming
 * activation ran (it may not have — the directory can be deleted, and uploads
 * can be moved).
 *
 * @return bool True when the directory exists and is writable.
 */
function qhta_woo_invoice_prepare_dir() {
	$dir = qhta_woo_invoice_dir();

	if ( ! wp_mkdir_p( $dir ) ) {
		return false;
	}

	// Apache: deny the whole directory. Both syntaxes, because 2.2 and 2.4
	// disagree and a server running 2.2 with a 2.4-only file silently serves
	// everything.
	$htaccess = $dir . '.htaccess';
	if ( ! file_exists( $htaccess ) ) {
		$rules = "# Generated by QHTA Woo Invoice. Invoices are private; they are served by PHP after an ownership check.\n"
			. "<IfModule mod_authz_core.c>\n\tRequire all denied\n</IfModule>\n"
			. "<IfModule !mod_authz_core.c>\n\tOrder allow,deny\n\tDeny from all\n</IfModule>\n";

		file_put_contents( $htaccess, $rules ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
	}

	// Anywhere directory listing is on, this is what gets listed instead.
	$index = $dir . 'index.php';
	if ( ! file_exists( $index ) ) {
		file_put_contents( $index, "<?php\n// Silence is golden.\n" ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
	}

	return wp_is_writable( $dir );
}

/**
 * The PDF filename for an order.
 *
 * Shape: `tax-invoice-<order number>-<hash>.pdf`. The order number is there so
 * a human looking in the directory can tell what they are looking at; the hash
 * is there so nobody on the outside can.
 *
 * The hash comes from wp_hash(), which is keyed on the site's AUTH salts. Two
 * consequences worth knowing:
 *
 *   - It is stable for the life of the site, so the name is derivable and no
 *     lookup is needed to find an existing invoice.
 *   - Rotating the salts changes it. The old PDFs are then orphaned rather than
 *     lost — QHTA_WOO_INVOICE_META_FILE still names them, and anything not
 *     found is regenerated on demand from the order, which is the source of
 *     truth anyway.
 *
 * @param WC_Order $order Order to name.
 * @return string
 */
function qhta_woo_invoice_filename( $order ) {
	$number = sanitize_file_name( (string) $order->get_order_number() );
	$hash   = substr( wp_hash( 'qhta-woo-invoice|' . $order->get_id() ), 0, 12 );

	return 'tax-invoice-' . $number . '-' . $hash . '.pdf';
}

/**
 * Absolute path to an order's PDF, whether or not it exists yet.
 *
 * Prefers the stored basename over the derived one so a file written before a
 * salt rotation is still found. The stored value is passed through basename()
 * before use: it is order meta, and order meta is writable by anything else on
 * the site, so it is not trusted to stay inside the invoice directory.
 *
 * @param WC_Order $order Order to locate.
 * @return string
 */
function qhta_woo_invoice_path( $order ) {
	$dir    = qhta_woo_invoice_dir();
	$stored = (string) $order->get_meta( QHTA_WOO_INVOICE_META_FILE );

	if ( '' !== $stored ) {
		$stored = basename( $stored );

		if ( '.pdf' === substr( $stored, -4 ) && file_exists( $dir . $stored ) ) {
			return $dir . $stored;
		}
	}

	return $dir . qhta_woo_invoice_filename( $order );
}

/**
 * Is there a PDF on disk for this order?
 *
 * @param WC_Order $order Order to test.
 * @return bool
 */
function qhta_woo_invoice_exists( $order ) {
	$path = qhta_woo_invoice_path( $order );

	return file_exists( $path ) && filesize( $path ) > 0;
}

/**
 * Write a rendered PDF to disk and record it on the order.
 *
 * Writes to a temporary name in the same directory and renames over the target,
 * so a download that lands mid-regeneration gets either the old invoice or the
 * new one, never a half-written file. rename() is atomic within a filesystem
 * and both paths are in the same directory, so it is.
 *
 * @param WC_Order $order Order being invoiced.
 * @param string   $pdf   Raw PDF bytes.
 * @return string|false Path written, or false on failure.
 */
function qhta_woo_invoice_save( $order, $pdf ) {
	if ( ! qhta_woo_invoice_prepare_dir() ) {
		qhta_woo_invoice_log( 'Invoice directory is missing or not writable: ' . qhta_woo_invoice_dir() );
		return false;
	}

	// Always write to the derived name. The stored one may be a pre-rotation
	// leftover, and regeneration should produce the current filename.
	$dir      = qhta_woo_invoice_dir();
	$filename = qhta_woo_invoice_filename( $order );
	$target   = $dir . $filename;
	$temp     = $target . '.tmp';

	// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
	if ( false === file_put_contents( $temp, $pdf ) ) {
		qhta_woo_invoice_log( 'Could not write invoice for order ' . $order->get_id() . ' to ' . $temp );
		return false;
	}

	if ( ! rename( $temp, $target ) ) {
		wp_delete_file( $temp );
		qhta_woo_invoice_log( 'Could not move invoice into place for order ' . $order->get_id() );
		return false;
	}

	$order->update_meta_data( QHTA_WOO_INVOICE_META_FILE, $filename );
	$order->update_meta_data( QHTA_WOO_INVOICE_META_TIME, time() );
	$order->save();

	/**
	 * Fires after an invoice PDF has been written.
	 *
	 * @param string   $target Absolute path to the PDF.
	 * @param WC_Order $order  Order it belongs to.
	 */
	do_action( 'qhta_woo_invoice_saved', $target, $order );

	return $target;
}

/**
 * Remove an order's PDF.
 *
 * Deletes both the stored filename and the derived one, so a salt rotation
 * cannot leave a stale copy behind that a later lookup would still find. The
 * meta is cleared either way — its job is to say "there is an invoice", and
 * after this there is not.
 *
 * @param WC_Order $order Order to clear.
 * @return void
 */
function qhta_woo_invoice_delete( $order ) {
	$dir     = qhta_woo_invoice_dir();
	$stored  = basename( (string) $order->get_meta( QHTA_WOO_INVOICE_META_FILE ) );
	$targets = array( qhta_woo_invoice_filename( $order ) );

	if ( '' !== $stored && '.pdf' === substr( $stored, -4 ) ) {
		$targets[] = $stored;
	}

	foreach ( array_unique( $targets ) as $name ) {
		if ( file_exists( $dir . $name ) ) {
			wp_delete_file( $dir . $name );
		}
	}

	$order->delete_meta_data( QHTA_WOO_INVOICE_META_FILE );
	$order->delete_meta_data( QHTA_WOO_INVOICE_META_TIME );
	$order->save();
}

/**
 * May this user have this order's invoice?
 *
 * Two ways in and no third: the order is theirs, or they administer the site.
 *
 * Deliberately not `current_user_can( 'view_order', $order_id )`. That meta
 * capability is mapped by WooCommerce and picks up whatever any other plugin
 * has filtered into `woocommerce_shop_manager_editable_roles` and friends — a
 * wider and more moveable surface than this needs. An invoice carries the
 * buyer's name, address and what they bought; the question being asked is
 * "is this your document?", and that is exactly the test below.
 *
 * Guest orders (customer ID 0) are unreachable by anyone but an administrator,
 * which is correct: with guest checkout off on this site there are none, and if
 * one appears there is no account it could belong to.
 *
 * @param WC_Order $order   Order being requested.
 * @param int|null $user_id User asking, or null for the current user.
 * @return bool
 */
function qhta_woo_invoice_can_access( $order, $user_id = null ) {
	$user_id = ( null === $user_id ) ? get_current_user_id() : (int) $user_id;

	if ( user_can( $user_id, 'manage_options' ) ) {
		return true;
	}

	$customer_id = (int) $order->get_customer_id();
	$allowed     = ( $user_id > 0 && $customer_id > 0 && $user_id === $customer_id );

	/**
	 * Filters whether a user may download an order's invoice.
	 *
	 * @param bool     $allowed Whether access is granted.
	 * @param WC_Order $order   Order being requested.
	 * @param int      $user_id User asking.
	 */
	return (bool) apply_filters( 'qhta_woo_invoice_can_access', $allowed, $order, $user_id );
}

/**
 * The download URL for an order's invoice.
 *
 * No nonce, and that is a decision rather than an omission. A nonce protects
 * against a request being made on the user's behalf without their intent, which
 * for a read-only download of their own document buys nothing; what it costs is
 * real, because WordPress nonces expire (12-24h) and this link is printed in
 * My Account and mailed around, where an expired one reads as a broken invoice.
 * The ownership check is the protection. Regeneration, which changes state,
 * does carry one.
 *
 * @param WC_Order $order  Order to link to.
 * @param string   $inline 'inline' to open in the browser's viewer, anything
 *                         else to download as a file.
 * @return string
 */
function qhta_woo_invoice_download_url( $order, $inline = '' ) {
	$args = array(
		'action'   => 'qhta_woo_invoice_download',
		'order_id' => $order->get_id(),
	);

	if ( 'inline' === $inline ) {
		$args['disposition'] = 'inline';
	}

	return add_query_arg( $args, admin_url( 'admin-post.php' ) );
}

/**
 * Serve an invoice PDF after checking who is asking.
 *
 * Registered for logged-out visitors too so they get sent to log in rather than
 * a bare "-1" from admin-post.php, which is what an unhandled nopriv action
 * produces and which looks like a broken link.
 *
 * @return void
 */
function qhta_woo_invoice_handle_download() {
	$order_id = isset( $_GET['order_id'] ) ? absint( wp_unslash( $_GET['order_id'] ) ) : 0; // phpcs:ignore WordPress.Security.NonceVerification.Recommended

	if ( ! is_user_logged_in() ) {
		// Send them to log in and come back, rather than telling a customer
		// with a perfectly good invoice that they are forbidden. My Account is
		// the door customers already use; wp-login.php is the fallback for a
		// site with no My Account page configured, where the alternative would
		// be redirecting to an empty string.
		$return = qhta_woo_invoice_download_url_by_id( $order_id );
		$login  = wc_get_page_permalink( 'myaccount' );

		$login = $login
			? add_query_arg( 'redirect_to', rawurlencode( $return ), $login )
			: wp_login_url( $return );

		wp_safe_redirect( $login );
		exit;
	}

	$order = $order_id ? wc_get_order( $order_id ) : false;

	// Same response for "no such order" and "not yours", so the handler cannot
	// be used to find out which order numbers exist.
	if ( ! $order || ! qhta_woo_invoice_can_access( $order ) ) {
		wp_die(
			esc_html__( 'Sorry, that invoice is not available to you.', 'qhta-woo-invoice' ),
			esc_html__( 'Invoice unavailable', 'qhta-woo-invoice' ),
			array( 'response' => 403 )
		);
	}

	$path = qhta_woo_invoice_ensure( $order );

	if ( ! $path ) {
		wp_die(
			esc_html__( 'Sorry, that invoice could not be produced. Please contact us.', 'qhta-woo-invoice' ),
			esc_html__( 'Invoice unavailable', 'qhta-woo-invoice' ),
			array( 'response' => 500 )
		);
	}

	// phpcs:ignore WordPress.Security.NonceVerification.Recommended
	$inline      = isset( $_GET['disposition'] ) && 'inline' === $_GET['disposition'];
	$disposition = $inline ? 'inline' : 'attachment';

	// What the customer sees the file called. Not the on-disk name — the hash in
	// that is an implementation detail and looks like a mistake in a downloads
	// folder.
	$download_name = 'tax-invoice-' . sanitize_file_name( (string) $order->get_order_number() ) . '.pdf';

	// Anything already buffered — a stray notice, a plugin's whitespace — would
	// be prepended to the PDF bytes and corrupt the file.
	while ( ob_get_level() > 0 ) {
		ob_end_clean();
	}

	nocache_headers();
	header( 'Content-Type: application/pdf' );
	header( 'Content-Disposition: ' . $disposition . '; filename="' . $download_name . '"' );
	header( 'Content-Length: ' . filesize( $path ) );
	header( 'X-Content-Type-Options: nosniff' );

	// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_readfile
	readfile( $path );
	exit;
}
add_action( 'admin_post_qhta_woo_invoice_download', 'qhta_woo_invoice_handle_download' );
add_action( 'admin_post_nopriv_qhta_woo_invoice_download', 'qhta_woo_invoice_handle_download' );

/**
 * Rebuild a download URL from an order ID alone.
 *
 * Used on the logged-out path, where the order has deliberately not been loaded
 * yet — an unauthenticated request should not cause a database read for an
 * arbitrary ID it supplied.
 *
 * @param int $order_id Order ID from the request.
 * @return string
 */
function qhta_woo_invoice_download_url_by_id( $order_id ) {
	return add_query_arg(
		array(
			'action'   => 'qhta_woo_invoice_download',
			'order_id' => absint( $order_id ),
		),
		admin_url( 'admin-post.php' )
	);
}
